networks:
  cheonil:
    name: cheonil
    driver: bridge
volumes:
  v-db:
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - v-db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: nice2122!
      MYSQL_DATABASE: cheonil
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: ko_KR.UTF-8
    networks:
      - cheonil
