version: '1.0'
networks:
  cheonil:
    name: cheonil
    driver: bridge
volumes:
  v-db:
services:
  db:
    container_name: db
    image: mariadb
    restart: always
    volumes:
      - v-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: nice2122!
      MYSQL_DATABASE: cheonil
    networks:
      - cheonil
  cheonil-server:
    container_name: cheonil-server
    image: ban/cheonil-restaurant-node
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      WS_PORT: 8100
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: cheonil
      DB_USER: root
      DB_PWD: nice2122!
    networks:
      - cheonil


