openapi: 3.0.3
info:
  title: 통합 서버 API
  description: 통합 DB 관련 API를 제공합니다.
  version: 1.0.0
paths:
  /api/menu:
    get:
      description: 메뉴 목록 조회
      responses:
        '200':
          description: 성공 (Created)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Menu'
    post:
      description: 메뉴 등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'
      responses:
        '201':
          description: 메뉴 등록 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Menu'
  /api/menu/{seq}:
    parameters:
        - name: seq
          in: path
          required: true
          schema:
            type: number
    put:
      description: 메뉴 수정
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Menu'
    delete:
      description: 메뉴 삭제
      responses:
        '204':
          description: 성공 (No Content)
  /api/menuCategory:
    get:
      description: 메뉴 카테고리 조회
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuCategory'
    post:
      description: 메뉴 카테고리 생성
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuCategory'
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuCategory'
  /api/menuCategory/{seq}:
    parameters:
        - name: seq
          in: path
          required: true
          schema:
            type: number
    put:
      description: 메뉴 카테고리 수정
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuCategory'
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuCategory'
    delete:
      description: 메뉴 카테고리 수정
      responses:
        '204':
          description: 성공 (No Content)
  /api/order:
    get:
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyOrder'
  /api/productInfos:
    description: 제품정보 목록 조회
    get:
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ProductInfo'
                  - allOf:
                      - $ref: '#/components/schemas/ProductInfo'
                      - type: object
                        properties:
                          products:
                            type: array
                            items:
                              allOf:
                                - $ref: '#/components/schemas/Product'
                                - type: object
                                  properties:
                                    unit:
                                      $ref: '#/components/schemas/Unit'
  /api/products:
    description: 제품 목록 조회
    get:
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /api/expenses:
    description: 지출 목록 조회
    get:
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Expense'
                  - type: object
                    properties:
                      store:
                        $ref: '#/components/schemas/Store'
                      expsPrds:
                        type: array
                        items:
                          allOf:
                            - $ref: '#/components/schemas/ExpenseProduct'
                            - type: object
                              properties:
                                product:
                                  allOf:
                                    - $ref: '#/components/schemas/Product'
                                    - type: object
                                      properties:
                                        unit:
                                          $ref: '#/components/schemas/Unit'
                                        prdInfo:
                                          $ref: '#/components/schemas/ProductInfo'
  /api/expenses/{seq}:
    get:
      parameters:
        - name: seq
          in: path
          required: true
          schema:
            type: number
      description: 지출 단건 조회
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
  /api/expenseCategories:
    description: 지출 카테고리 목록 조회
    get:
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExpenseCategory'
    post:
      description: 지출 카테고리 등록
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExpenseCategory'
  /api/expenseCategories/{seq}:
    parameters:
      - name: seq
        in: path
        required: true
        schema:
          type: string
    get:
      description: 지출 카테고리 단건 조회
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseCategory'
    patch:
      description: 지출 카테고리 수정
      responses:
        '200':
          description: 성공 (OK)
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExpenseCategory'
    delete:
      description: 지출 카테고리 수정
      responses:
        '204':
          description: 삭제 NO CONTENT
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Ok:
      description: 성공 (OK)
    Created:
      description: 성공 (Created)
      headers:
        Location:
          schema:
            type: string
            example: /api/{resources}/{resource id}
    NoContent:
      description: 성공 (No Content)
    Unauthorized:
      description: 인증 실패
    Forbidden:
      description: 요청 제한
    IDNotExist:
      description: 해당 식별키가 존재하지 않습니다
    LOGIN_FAIL:
      description: 아이디 or 비밀번호가 옳지 않습니다
    LOGIN_FAIL_EXCEED:
      description: 로그인 시도 횟수를 초과하였습니다
  schemas:
    MenuCategoryNSC:
      type: object
      properties:
        seq:
          description: 메뉴 카테고리 Seq
          type: string
        name:
          description: 메뉴 카테고리 명
          type: string
        options:
          description: 추가정보
          type: string
    MenuCategory:
      allOf:
        - $ref: '#/components/schemas/MenuCategoryNSC'
        - type: object
          properties:
            createdAt:
              description: 생성시간
              type: string
              format: date-time
            updatedAt:
              description: 수정시간
              type: string
              format: date-time
    MenuNSC:
      type: object
      properties:
        seq:
          description: 메뉴 Seq
          type: string
        ctgSeq:
          description: 메뉴 카테고리 Seq
          type: string
        name:
          description: 메뉴 명
          type: string
        abv:
          description: 이름 약어
          type: string
        price:
          description: 가격
          type: string
        cmt:
          description: 비고
          type: string
        options:
          description: 추가정보
          type: string
    Menu:
      allOf:
        - $ref: '#/components/schemas/MenuNSC'
        - type: object
          properties:
            createdAt:
              description: 생성시간
              type: string
              format: date-time
            updatedAt:
              description: 수정시간
              type: string
              format: date-time
    ExpenseNSC:
      type: object
      properties:
        seq:
          description: 지출 SEQ
          type: string
        ctgSeq:
          description: 카테고리 SEQ
          type: string
        storeSeq:
          description: 매장 SEQ
          type: string
        name:
          description: 지출명
          type: string
        amount:
          description: 금액
          type: string
        expenseAt:
          description: 지출일
          type: string
          format: date-time
        cmt:
          description: 비고
          type: string
        options:
          description: 추가 정보
          type: string
    Expense:
      allOf:
        - $ref: '#/components/schemas/ExpenseNSC'
        - type: object
          properties:
            updatedAt:
              description: 수정시간
              type: string
              format: date-time
    ProductInfoNSC:
      type: object
      properties:
        seq:
          description: 제품 Seq
          type: string
        suplSeq:
          description: 식자재 Seq
          type: string
        name:
          description: 식자재 명
          type: string
        cmt:
          description: 비고
          type: string
        options:
          description: 추가 정보
          type: string
    ProductInfo:
      allOf:
        - $ref: '#/components/schemas/ProductInfoNSC'
        - type: object
          properties:
            createdAt:
              description: 생성시간
              type: string
              format: date-time
            updatedAt:
              description: 수정시간
              type: string
              format: date-time
    SupplyNSC:
      type: object
      properties:
        seq:
          description: 식자재 Seq
          type: string
        name:
          description: 식자재 명
          type: string
        options:
          description: 추가 정보
          type: string
    Supply:
      allOf:
        - $ref: '#/components/schemas/SupplyNSC'
        - type: object
          properties:
            createdAt:
              description: 생성시간
              type: string
              format: date-time
            updatedAt:
              description: 수정시간
              type: string
              format: date-time
    MyOrderNSC:
      type: object
      properties:
        seq:
          description: 주문 Seq
          type: string
        storeSeq:
          description: 매장 Seq
          type: string
        amount:
          description: 총 금액
          type: string
        status:
          description: 'READY: 준비, COOKED: 조리 완료, PAID: 결제 완료'
          type: string
        orderAt:
          description: 주문 시간
          type: string
          format: date-time
        cookedAt:
          description: 조리완료 시간
          type: string
          format: date-time
        cmt:
          description: 비고
          type: string
    MyOrder:
      allOf:
        - $ref: '#/components/schemas/MyOrderNSC'
        - type: object
          properties:
            updatedAt:
              description: 수정시간
              type: string
              format: date-time
    Setting:
      type: object
      properties:
        seq:
          description: 설정 Seq
          type: string
        config:
          description: 설정 정보
          type: string
    StoreCategoryNSC:
      type: object
      properties:
        seq:
          description: 매장 카테고리 Seq
          type: string
        placeCtgSeq:
          description: 장소 카테고리 Seq
          type: string
        name:
          description: 매장 카테고리 명
          type: string
        options:
          description: 추가정보
          type: string
    StoreCategory:
      allOf:
        - $ref: '#/components/schemas/StoreCategoryNSC'
        - type: object
          properties:
            createdAt:
              description: 생성시간
              type: string
              format: date-time
            updatedAt:
              description: 수정시간
              type: string
              format: date-time
    OrderMenu:
      type: object
      properties:
        menuSeq:
          description: 메뉴 Seq
          type: string
        orderSeq:
          description: 주문 Seq
          type: string
        price:
          description: 가격 menu는 가격이 바뀔수가 있음
          type: string
        cnt:
          description: 수량
          type: string
    Unit:
      type: object
      properties:
        seq:
          description: 단위 SEQ
          type: string
        name:
          description: 단위
          type: string
        isUnitCnt:
          description: 단위수량 여부
          type: string
    PlaceCategory:
      type: object
      properties:
        seq:
          description: 장소 카테고리 Seq
          type: string
        name:
          description: 장소 카테고리 명
          type: string
        cmt:
          description: 비고
          type: string
        options:
          description: 추가정보
          type: string
    StoreNSC:
      type: object
      properties:
        seq:
          description: 매장 Seq
          type: string
        ctgSeq:
          description: 매장 카테고리 Seq
          type: string
        placeCtgSeq:
          description: 장소 카테고리 Seq
          type: string
        name:
          description: 매장 명
          type: string
        cmt:
          description: 기타 정보
          type: string
        latitude:
          description: 위도
          type: string
        longitude:
          description: 경도
          type: string
        options:
          description: 추가정보
          type: string
    Store:
      allOf:
        - $ref: '#/components/schemas/StoreNSC'
        - type: object
          properties:
            createdAt:
              description: 생성시간
              type: string
              format: date-time
            updatedAt:
              description: 수정시간
              type: string
              format: date-time
    OrderMenuRsv:
      type: object
      properties:
        menuSeq:
          description: 메뉴 Seq
          type: string
        orderRsvSeq:
          description: 주문예약 Seq
          type: string
        price:
          description: 가격 menu는 가격이 바뀔수가 있음
          type: string
        cnt:
          description: 수량
          type: string
    Product:
      type: object
      properties:
        seq:
          description: SEQ
          type: string
        prdInfoSeq:
          description: 제품 SEQ
          type: string
        unitSeq:
          description: 단위 SEQ
          type: string
        unitCntList:
          description: 단위수량 목록
          type: string
    ExpenseCategory:
      type: object
      properties:
        seq:
          description: 지출 카테고리 SEQ
          type: string
        path:
          description: 카테고리명
          type: string
        options:
          description: 추가 정보
          type: string
    Payment:
      type: object
      properties:
        seq:
          description: 결재 Seq
          type: string
        orderSeq:
          description: 주문 Seq
          type: string
        amount:
          description: 결재 금액
          type: string
        payType:
          description: 'CASH: 현금, CARD: 카드'
          type: string
        payAt:
          description: 지급날짜
          type: string
          format: date-time
    ExpenseProduct:
      type: object
      properties:
        expsSeq:
          description: 지출 Seq
          type: string
        prdSeq:
          description: 제품 SEQ
          type: string
        cnt:
          description: 수량
          type: string
        price:
          description: 가격
          type: string
        unitCnt:
          description: 단위수량
          type: string
        cmt:
          description: 비고
          type: string
    OrderRsvNSC:
      type: object
      properties:
        seq:
          description: 주문예약 Seq
          type: string
        storeSeq:
          description: 매장 Seq
          type: string
        amount:
          description: 총 금액
          type: string
        rsvTime:
          description: HH:MM
          type: string
        dayType:
          description: 요일
          type: string
        cmt:
          description: 비고
          type: string
        options:
          description: 추가정보
          type: string
    OrderRsv:
      allOf:
        - $ref: '#/components/schemas/OrderRsvNSC'
        - type: object
          properties:
            createdAt:
              description: 생성시간
              type: string
              format: date-time
            updatedAt:
              description: 수정시간
              type: string
              format: date-time
